/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Assest;

/**
 *
 * @author Anushka Isuru
 */
public class mbg extends javax.swing.JPanel {

    /**
     * Creates new form mbg
     */
    public mbg() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setBackground(new java.awt.Color(6, 14, 28));
        setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 145, 196)));

        
    }
}
